### ISSUE TITLE
Настройка github action для проброса на vps

### ISSUE THREAD

**Issue by Lightthouse** [bet55/kinopolka#3]
Создать пайплайн, который при пуле в master пробрасывает код на vps и разворачивает докер

```yaml
name: Deploy to Remote Server

on:
  push:
    branches:
      - master    # Triggers on push to master branch
  workflow_dispatch: # Allows manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy to remote server
        run: |
          ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} '
            cd ${{ secrets.REMOTE_DIR }} &&
            git fetch origin master &&
            git reset --hard origin/master
          '
```
1. mkdir -p .github/workflows
2.  touch .github/workflows/deploy.yml
3. Copy the above YAML content into the `deploy.yml` file
4. Add the required secrets in your GitHub repository settings
5. Make sure your remote server:
   - Has Git installed
